# environment
info: Train_OfflineHER_FetchReach
env: FetchReach-v1
use_her: True
norm_obs: False
seed: 5
strategy: offline
curriculum: False

# buffer
use_PER: False
per_alpha: 0.7
per_beta: 0.5
buffer_size: 1000000
replay_k: 8

# network
hidden_sizes: [64, 64]

# train
actor_lr: 1.0e-3
critic_lr: 1.0e-3
start_timesteps: 32000 # warmup
epoch: 10 # save times
step_per_epoch: 32000 # save interval (50repeat)
step_per_collect: 3200 #(64path) after collect #, update
update_per_step: 1 # repeat update time
estimation_step: 1 # look ahead time steps
batch_size: 256

# parallel
device: cuda # cuda
training_num: 2
test_num: 2

# Algorithm
alpha: 0.2 # entropy regularization coefficient
auto_alpha: True
alpha_lr: 0.0003 # works if open auto alpha
tau: 0.005
gamma: 0.95

# dir
logdir: log
resume_path: null
save_render: False

# render
watch_train: False # if show demo directly
record_test: False
render: 0.00 # render time rate